[package]
name = "url-shortener"
version = "0.1.0"
authors = ["Rohan Debroy <debroy.debroy2017@gmail.com>"]
edition = "2021"
publish = false

[workspace]
members = [".", "migration"]
resolver = "2"

[dependencies]
actix-web = "4.4.1"
nanoid = "0.4.0"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
migration = { path = "./migration" }
dotenvy = "0.15.7"
sea-orm = { version = "0.12.10", features = [
  "sqlx-postgres",
  "runtime-actix-rustls",
] }
