version: '3'
services:
  db:
    container_name: url-shortener-sea-orm-new
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:

# version: '3.1'

# services:
#   db:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: toor
#     volumes:
#       - mysql-data:/var/lib/mysql
#     ports:
#       - "3306:3306"

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

# volumes:
#   mysql-data:
